ALTER TABLE users
ADD COLUMN IF NOT EXISTS phonenum VARCHAR(30);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS debit_card_num TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS card_expiry VARCHAR(10);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS card_cvc TEXT;
